### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jdonszelmann** [EmilHernvall/dnsguide#13]
Forgive me if I misread, but as it is now this project doesn't seem to have a license associated with it. What do you find acceptable?

**Comment by JasonCheng1** [comment]
Also interested to know if there is any restriction on the use of the source code? a.k.a your open-source license

**Comment by EmilHernvall** [comment]
I’m thinking CC for the text and MIT for the source code. I’ll try to add a note in the next few days.

**Comment by EmilHernvall** [comment]
Sorry about the delay on this. Added MIT license.
