### ISSUE TITLE
DNS compression when writing labels

### ISSUE THREAD

**Issue by ema2159** [EmilHernvall/dnsguide#23]
Hello. I am currently following your tutorial (great tutorial by the way), and am currently implementing the write methods for the stub resolver section. However, there is something that I don't quite understand: In chapter 1, the `read_qname` function implemented this label compression idea by jumping to and reusing old labels. However, in chapter two, the `write_qname` function doesn't implement the same idea. Did you just chose not to implement it, or is there something I am missing?

Thanks beforehand!

**Comment by EmilHernvall** [comment]
Yeah, that’s it. For simplicity, I omitted it, since it’s an optional feature. I believe I did implement it in EmilHernvall/hermes though, so if you want to see one way to do it, check there.

**Comment by ema2159** [comment]
Thanks a lot for the clarification Emil. I will give it a try myself and then take a look at hermes. 

Regards.
