### ISSUE TITLE
Enhancement suggestion: pi-hole-like DNS blocking by blacklisting

### ISSUE THREAD

**Issue by leodutra** [EmilHernvall/dnsguide#8]
Pi-Hole does a great job, but its implementation is not over a thread-safe and blazing fast language like Rust.
It would be awesome to see the full DNS could integrate with it, and maybe embed a port of if in the long-term future.

**Comment by EmilHernvall** [comment]
Thanks for the suggestion! I think it's an interesting idea, but not something I'm interested in pursuing myself. Hopefully this guide can help you get started if you want to give it a shot yourself, though!
